language: node_js

node_js:
  - "6.10.3"

services:
  - docker

branches:
  only:
  - master

before_install:
  - sudo docker pull ubuntu:xenial
  - sudo docker build -t rclnodejs .
  - sudo docker run --rm rclnodejs bash -c "/bin/versions/node/v6.10.3/bin/node -v"

script:
