language: node_js

services:
  - docker

branches:
  only:
  - master

before_install:
  - sudo docker pull ubuntu:xenial
  - sudo docker build -t rclnodejs .

script:
  - sudo docker run --rm rclnodejs bash -i -c 'npm -v && node -v'
