language: node_js

node_js:
  - "6.10.3"

services:
  - docker

branches:
  only:
  - master

before_install:
  - sudo docker pull ubuntu:xenial
  - sudo docker build -t rclnodejs .
  - sudo docker run --rm rclnodejs bash -c 'source $HOME/.nvm/nvm.sh && nvm install v6.10.3 && node -v'

script:
